version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '3554:80'
      - '81:81'
      - '3555:443'
    environment:
      DB_MYSQL_HOST: 'npmdb'
      DB_MYSQL_USER: 'npm'
      DB_MYSQL_NAME: 'npm'
      DB_MYSQL_PORT: 3556
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - npm_db
  npm_db:
    image: 'jc21/mariadb-aria:10.4'
    hostname: 'npmdb'
    restart: always
    ports:
      - '3556:3306'
    environment:
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql